# SwiftLint Configuration for DiscordLite
# Documentation: https://realm.github.io/SwiftLint/

# Paths to include/exclude
included:
  - DiscordLite
  - DiscordLiteTests

excluded:
  - Pods
  - .build
  - DerivedData
  - .swiftpm
  - DiscordLite.xcodeproj

# Analyzer rules (require 'swiftlint analyze')
analyzer_rules:
  - unused_declaration
  - unused_import

# Opt-in rules (not enabled by default)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments for development
  - trailing_comma # Handled by swift-format

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - ID
    - url
    - URL
    - vm

nesting:
  type_level:
    warning: 2
    error: 3

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - ID
    - URL
    - VM

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    message: "Use LoggerService instead of print() for logging"
    severity: warning
    excluded:
      - ".*Tests\\.swift"

  no_force_try:
    name: "No Force Try"
    regex: 'try!\s'
    message: "Avoid force try - handle errors properly with do-catch or Result types"
    severity: warning

# Reporter
reporter: "xcode" # Use Xcode-compatible format for better IDE integration
